services:
  db:
    image: postgres:17
    container_name: movdin-db
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - internal

  app:
    build: .
    container_name: movdin-app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
      - cloudflared_net

networks:
  internal:
  cloudflared_net:
    external: true
